kpanda:
  - "docs/en/docs/kpanda/**/*"
  - "docs/zh/docskpanda/**/*"

skoala:
  - "docs/en/docsskoala/**/*"
  - "docs/zh/docsskoala/**/*"

mspider:
  - "docs/en/docsmspider/**/*"
  - "docs/zh/docsmspider/**/*"

en:
  - "docs/en/**/*"

zh:
  - "docs/zh/**/*"
