# Project information
site_name: DaoCloud Enterprise
site_url: https://docs.daocloud.io/
site_author: DaoCloud
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project

# copyright
copyright: Copyright &copy; 2016 - 2022 DaoCloud

# Repository
repo_name: DaoCloud/daocloud-docs
repo_url: https://github.com/DaoCloud/daocloud-docs
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  # custom_dir: !ENV [THEME_DIR, "material"]

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  include_homepage_in_sidebar: false

  # Static files
  static_templates:
    - 404.html

  language: "zh"
  features:
    - content.code.annotate
    - content.tooltips
    # - navigation.indexes
    - navigation.tabs
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.tracking
    # - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    # - toc.integrate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: images/DaoCloud.svg
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\\s\\u200b\\-]'
  - mermaid2
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

  - git-revision-date #每页底部显示文档最后更新日期，安装 pip install mkdocs-git-revision-date-plugin
  - git-revision-date-localized #每个页面底部添加本地化更新和创建日期，安装pip install mkdocs-git-revision-date-localized-plugin
    # - type: datetime  #日期格式，有效值为date、datetime、iso_date、iso_datetimetimeago
    # - fallback_to_build_date: true  #默认false，启用则回退到mkdocs build执行的时间
    # - enable_creation_date: true  #最后更新日期旁边显示与页面关联的文件的创建日期

  # auto desgin nav in dirs
  # - awesome-pages:
  #     filename: .pages.yml
  #     collapse_single_pages: true
  #     strict: false
  - tags:
      tags_file: stylesheets/tags.md

# Customization
extra:
  
  homepage: /zh/

  # switch language
  alternate:
    - link: /zh/
      name: zh - 简体中文
      lang: zh
    - link: /en/
      name: en - English
      lang: en
  generator: false

# Customization Javascript
extra_javascript:
  - stylesheets/zoom_image.js
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

# Customization css
extra_css:
  - stylesheets/custom.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: 导航
      toc_depth: 5
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: daocloud
      repo: daocloud-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # - pymdownx.critic

  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md

# Page tree
nav:
  - 首页: zh/index.md
  - 帮助文档:
      - DCE 产品介绍:
          - 什么是 DCE5.0: zh/dce/what-is-dce.md
          - DCE 生态模块: zh/dce/modules.md
          - 平台功能: zh/dce/features.md
          - 系统架构: zh/dce/architect.md
          - 为什么选择 DCE: zh/dce/whyus.md
          - 适用场景: zh/dce/scenarios.md
          - DCE 5.0 重要更新: zh/dce/news.md
      - 容器管理:
          - 容器管理介绍:
              - 什么是容器管理: zh/kpanda/03ProductBrief/WhatisKPanda.md
              - 功能总览: zh/kpanda/03ProductBrief/Features.md
              - 竞争优势: zh/kpanda/03ProductBrief/Benefits.md
              - 适用场景: zh/kpanda/03ProductBrief/Scenarios.md
              - 基本概念: zh/kpanda/03ProductBrief/Concepts.md
          - 集群管理:
              - 创建集群: zh/kpanda/07UserGuide/Clusters/CreateCluster.md
              - 接入集群: zh/kpanda/07UserGuide/Clusters/JoinACluster.md
              - 使用 kubectl 访问集群: zh/kpanda/07UserGuide/Clusters/clusterwithcert.md
              - 集群角色: zh/kpanda/07UserGuide/Clusters/ClusterRole.md
              - 集群状态: zh/kpanda/07UserGuide/Clusters/ClusterStatus.md
          - 工作负载:
              - 通过镜像创建无状态负载: zh/kpanda/07UserGuide/Workloads/CreateDeploymentByImage.md
              - 通过镜像创建有状态负载: zh/kpanda/07UserGuide/Workloads/CreateStatefulSetByImage.md
              - 通过镜像创建守护进程集: zh/kpanda/07UserGuide/Workloads/CreateDaemonSetByImage.md
              - 通过镜像创建定时任务: zh/kpanda/07UserGuide/Workloads/CreateCronJobByImage.md
              - 通过镜像创建任务: zh/kpanda/07UserGuide/Workloads/CreateJobByImage.md
              - 参数配置说明:
                  - 任务的参数说明: zh/kpanda/07UserGuide/Workloads/PodConfig/JobParameters.md
                  - 生命周期: zh/kpanda/07UserGuide/Workloads/PodConfig/lifescycle.md
                  - 环境变量: zh/kpanda/07UserGuide/Workloads/PodConfig/EnvironmentVariables.md
                  - 健康检查: zh/kpanda/07UserGuide/Workloads/PodConfig/healthcheck.md
                  - 集群调度: zh/kpanda/07UserGuide/Workloads/PodConfig/SchedulingPolicy.md
          - 服务与路由:
              - 创建服务: zh/kpanda/07UserGuide/ServicesandRoutes/CreatingServices.md
              - 创建路由: zh/kpanda/07UserGuide/ServicesandRoutes/CreatingIngress.md
          - 配置与密钥:
              - 创建配置项: zh/kpanda/07UserGuide/ConfigMapsandSecrets/CreatConfigMap.md
              - 使用配置项: zh/kpanda/07UserGuide/ConfigMapsandSecrets/UsedConfigMap.md
      - 微服务治理:
          - 微服务治理介绍:
              - 功能总览: zh/skoala/intro/features.md
              - 使用场景: zh/skoala/intro/scenarios.md
              - 竞争优势: zh/skoala/intro/advantages.md  
              - 系统架构: zh/skoala/intro/architecture.md
              - 组件版本: zh/skoala/intro/components.md
              - 名词解释: zh/skoala/intro/GLOSSARY.md
          - 微服务管理:
              - 托管注册中心管理: zh/skoala/ms-management/hosted/create-registry.md
              - 微服务命名空间: zh/skoala/ms-management/hosted/namespace.md
          - 微服务网关:
              - 网关管理:
                  - 创建网关: zh/skoala/ms-gateway/gateway/create-gateway.md
                  - 查看网关详情: zh/skoala/ms-gateway/gateway/check-details.md
                  - 诊断网关: zh/skoala/ms-gateway/gateway/delete-gateway.md
                  - 更新网关: zh/skoala/ms-gateway/gateway/update-gateway.md
                  - 删除网关: zh/skoala/ms-gateway/gateway/delete-gateway.md
              - API:
                  - 管理 API: zh/skoala/ms-gateway/api/manage-api.md
                  - 配置 API 策略: zh/skoala/ms-gateway/api/api-policy.md
              - 域名:
                  - 管理域名: zh/skoala/ms-gateway/domain/manage-domain.md
                  - 配置域名策略: zh/skoala/ms-gateway/domain/domain-policy.md
      - 中间件:
          - RabbitMQ 消息队列:
              - 什么是 RabbitMQ: zh/middleware/rabbitmq/intro/what.md
              - 功能说明: zh/middleware/rabbitmq/intro/features.md
              - 竞争优势: zh/middleware/rabbitmq/intro/benefits.md
              - 适用场景: zh/middleware/rabbitmq/intro/scenarios.md
              - 基本概念: zh/middleware/rabbitmq/intro/concepts.md
              - 安装 RabbitMQ: zh/middleware/rabbitmq/quickstart/install.md
              - 更新 RabbitMQ: zh/middleware/rabbitmq/userguide/update.md
              - 删除 RabbitMQ: zh/middleware/rabbitmq/userguide/delete.md
              - 查看消息队列: zh/middleware/rabbitmq/userguide/view.md
              - 数据迁移: zh/middleware/rabbitmq/userguide/migrate.md
              - 实例监控: zh/middleware/rabbitmq/userguide/insight.md
          - Elasticsearch 搜索服务:
              - 什么是 Elasticsearch: zh/middleware/elastic-search/intro/what.md
              - 功能说明: zh/middleware/elastic-search/intro/features.md
              - 竞争优势: zh/middleware/elastic-search/intro/benefits.md
              - 适用场景: zh/middleware/elastic-search/intro/scenarios.md
              - 基本概念: zh/middleware/elastic-search/intro/concepts.md
              - 首次使用 Elasticsearch: zh/middleware/elastic-search/userguide/login.md
              - 创建 Elasticsearch 实例: zh/middleware/elastic-search/userguide/create.md
              - 更新 Elasticsearch 实例: zh/middleware/elastic-search/userguide/edit.md
              - 删除 Elasticsearch 实例: zh/middleware/elastic-search/userguide/delete.md
              - Elasticsearch 集群容量规划: zh/middleware/elastic-search/userguide/cluster-capacity-plan.md
              - 查看列表: zh/middleware/elastic-search/userguide/view.md
              - 概览: zh/middleware/userguide/elastic-search/basic.md
              - 实例监控: zh/middleware/elastic-search/userguide/monitor.md
          - MySQL 数据库:
              - 什么是 MySQL: zh/middleware/mysql/intro/what.md
              - 功能说明: zh/middleware/mysql/intro/features.md
              - 竞争优势: zh/middleware/mysql/intro/benefits.md
              - 基本概念: zh/middleware/mysql/intro/concepts.md
              - 安装 MySQL: zh/middleware/mysql/quickstart/install.md
              - 创建 MySQL: zh/middleware/mysql/userguide/create.md
              - 更新 MySQL: zh/middleware/mysql/userguide/update.md
              - 删除 MySQL: zh/middleware/mysql/userguide/delete.md
  - 视频教程:
      - 容器管理: zh/videos/kpanda.md
      - 全局管理: zh/videos/ghippo.md
      - 可观测性: zh/videos/insight.md
      - 应用工作台: zh/videos/amamba.md
      - 服务网格: zh/videos/mspider.md
      - 微服务引擎: zh/videos/skoala.md
      - 中间件: zh/videos/mcamel.md
  - 博客:
      - DCE开发背景: zh/blogs/blog00.md
      - eBPF与可观测性: zh/blogs/blog01.md
  - 开源社区:
      - CloudTTY: zh/community/cloudtty.md
      - Clusterpedia: zh/community/clusterpedia.md
      - HwameiStor: zh/community/hwameistor.md
      - KLTS: zh/community/klts.md
      - Kubean: zh/community/kubean.md
      - Merbridge: zh/community/merbridge.md
      - Spiderpool: zh/vidcommunityeos/spiderpool.md
