---
name: 🛑 Request a feature in the DaoCloud Enterprise Documents
about: If you have feature requests for DaoCloud Enterprise Documents
title: ''
labels: feature
assignees: ''

---

<!--
👋 You're opening a request for an enhancement in the GitHub Actions **runner application**.

If you have a feature request that is relevant to this repository, then please include the information below:
-->

**Describe the enhancement**
A clear and concise description of what the features or enhancement you need.

**Additional information**
Add any other context about the feature here.

NOTE: if the feature request has been agreed upon then we will add you to the thank you list.