---
name: 🛑 Report a bug in the DaoCloud Enterprise Documents
about: If you have issues with DaoCloud Enterprise Documents, Please follow the "support for GitHub Actions" link, below.
title: ''
labels: bug
assignees: ''

---

<!--
👋 You're opening a bug report against the DaoCloud Enterprise Documents.
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.