title: 产品介绍
nav:
- 产品介绍:
  - 什么是 DCE5.0: dce-brief/what-is-dce.md
  - DCE 生态模块: dce-brief/modules.md
  - 平台功能: dce-brief/features.md
  - 系统架构: dce-brief/architect.md
  - 为什么选择 DCE: dce-brief/whyus.md
  - 适用场景: dce-brief/scenarios.md
  - DCE 5.0 重要更新: dce-brief/news.md
